apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cn4x00ozv-nodejs 
  janus-idp.io/tekton: cn4x00ozv-nodejs
  backstage.io/kubernetes-id: cn4x00ozv-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cn4x00ozv-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml